[project]
name = "my_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cmakelang>=0.6.13",
    "codespell>=2.4.1",
    "conan>=2.12.1",
]
