name: CMake on windows platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        include:
          - c_compiler: cl
            cpp_compiler: cl
            ci_os: windows
            activate_cmd: .venv\Scripts\activate.bat

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
    - run: uv sync --frozen --no-install-project

    - name: Configure CMake
      run: |
        ${{ matrix.activate_cmd }}
        cmake --preset ci-${{ matrix.ci_os }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -D CONAN_COMMAND=${{ github.workspace }}\.venv\Scripts\conan.exe

    - name: Build
      run: cmake --build --preset ci-${{ matrix.ci_os }}-release

    - name: Test
      run: ctest --preset ci-${{ matrix.ci_os }}-test-release

    - name: Package
      run: cpack --preset ci-${{ matrix.ci_os }}-package

    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/build/${{ matrix.ci_os }}/docs
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
      
